# This workflow will build a docker container, publish it to Github Registry.
name: Build and Deploy Docker Container
on:
  - push
# on:
#   release:
#     types: [created]
#   workflow_dispatch:

env:
  IMAGE_NAME: dotsuite/webapp
  PACKAGE_PATH: webapp

jobs:
  build-publish-application:
    strategy:
      fail-fast: false

    name: Build and deploy container
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Container registry.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_KEY }}

      # Builds and push the Docker image.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: ./
          file: ./packages/${{env.PACKAGE_PATH}}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{secrets.REGISTRY_SERVER}}/${{env.IMAGE_NAME}}:latest

      - name: Export digest
        run: |
            mkdir -p /tmp/digests
            digest="${{ steps.build.outputs.digest }}"
            touch "/tmp/digests/${digest#sha256:}"
  
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-webapp
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
